---
name: Class-Private
version: 0.04
author:
  - 'Leon Timmermans <leont@cpan.org>'
abstract: Private hashes for your objects
license: perl
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Class-Private
  license: http://dev.perl.org/licenses/
  repository: http://github.com/Leont/class-private/tree
configure_requires:
  Module::Build: 0
requires:
  perl: 5.01
build_requires:
  Module::Build: 0
  Test::More: 0
  Test::NoWarnings: 0
provides:
  Class::Private:
    file: lib/Class/Private.pm
    version: 0.04
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
keywords:
  - OO
  - privacy
